// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqyfzgtqztjwzsgpnijf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxeWZ6Z3RxenRqd3pzZ3BuaWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzI0NjEsImV4cCI6MjA2ODM0ODQ2MX0.22GjICkuGEkVvcSLwRWIwJiPji-UyOm-blEyYNzIBi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});